name: 'Build Information'
description: 'Outputs build environment and system information'
inputs:
  environment:
    description: 'Deployment environment'
    required: true
  choice:
    description: 'Test choice'
    required: false
  git_ref:
    description: 'GitHub reference'
    required: true
runs:
  using: 'composite'
  steps:
    - run: |
        java -version
        mvn -version
        google-chrome --version
        helm version
        echo "Deployment to ${{ inputs.environment }}"
        echo "Tests ${{ inputs.choice }}"
        echo "GitRef ${{ inputs.git_ref }}"
        cd terraform
        chmod +x script.sh
        ./script.sh
        test=$backups
        export testall=$backups
        echo "test=$test" >> $GITHUB_ENV
        echo "testall=$backups" >> $GITHUB_ENV
      shell: bash
      id: step1
