name: Manage Alerts

on:
  workflow_call:
    inputs:
      alerts:
        description: 'Choose alerts: enable or disable'
        required: true
        default: 'enable'
        type: string
jobs:
  manage_alerts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг для включения alerts
      - name: Enable alerts
        if: ${{ github.event.inputs.alerts == 'enable' }}
        run: |-
          echo "Enabling alerts..."
          # ваш код для включения

      # Шаг для выключения alerts
      - name: Disable alerts
        if: ${{ github.event.inputs.alerts == 'disable' }}
        run: |-
          echo "Disabling alerts..."
          # ваш код для выключения
