# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Test echo
        env: 
          TESTTT: ${{ secrets.BACKLANUES }}
        run: |
            echo $TESTTT  > back.values.yaml
            cat back.values.yaml
            ls -la
