# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: ls /Applications
      - name: Run tests
        run: |
            sudo xcode-select --switch /Applications/Xcode_15.0.1.app
            xcodebuild -runFirstLaunch
            gem install fastlane
            xcodebuild -version
      - name: git clone 
        run: |
            git clone https://${{ secrets.AZURETOKEN }}@dev.azure.com/ArtSparrow/Smart/_git/msk-notes-iOS-SDK
            git clone https://${{ secrets.AZURETOKEN }}@dev.azure.com/ArtSparrow/Smart/_git/msk-notes2_0-ios
            cd msk-notes2_0-ios
            git checkout fastlanedone
            pwd
            ls -la
      - name: Pod install
        run: |
            cd /Users/runner/work/lesson1/lesson1/msk-notes2_0-ios
            pod install 
      - name: Run Fastlane
        run: |
            cd /Users/runner/work/lesson1/lesson1/msk-notes2_0-ios
            fastlane build_and_upload
