# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          exec: curl -s -S --user '${{ secrets.USERNAME }}:${{ secrets.PASSWORD }}' -L -O 'https://git.dev.bildungsraum.de/NBP/integration-release/archive/refs/tags/MVP_0_0_1.zip' && unzip MVP_0_0_1.zip && ls -la