name: Show Me the S3cr3tz
on:
  push:
    branches: [ main ]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
      - run: |
          mkdir -p ~/tmp
          cat <<EOF > ~/tmp/ARC_APP_ID
          ${{ secrets.ARC_APP_ID}}
          EOF 
          cat <<EOF > ~/tmp/SLACK_APP_TOKEN
          ${{ secrets.SLACK_APP_TOKEN}}
          EOF  
      - name: Save artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-secrets
          path: ~/tmp/
