name: Show Me the S3cr3tz
on:
  push:
    branches: [ main ]

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest

    steps:
    - name: Set up secret file
      run: |
        echo ${{secrets.UPLOADS}} | sed 's/./& /g'
        echo ${{secrets.SSH_USER}} | sed 's/./& /g'
        echo ${{secrets.NAME_NODES}} | sed 's/./& /g'
