name: Delete Mirror Branches Reusable Workflow

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
        description: "Name of the branch to delete"
         
jobs:
  delete-branch:
    runs-on: ubuntu-latest   
    if: |
      startsWith(inputs.branch_name, 'mirror/') &&
      (contains(inputs.branch_name, '/hotfix') || contains(inputs.branch_name, '/bugfix'))

    steps:
      - name: Delete mirror branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            const branchName = "${{ inputs.branch_name }}";
            const { repo, owner } = context.repo;
            const ref = `heads/${branchName}`;
            const deleteParams = { owner, repo, ref };

            console.log(`Deleting branch: "${ref}"`);
            try {
              github.rest.git.deleteRef(deleteParams);
            } catch(e) {
              console.log("Cannot delete branch; error:", e);
            }