name: Deploy { BACKEND FRONTEND WEBSITE } to DEV server 

on:
  workflow_dispatch:


jobs:
  BACKEND:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Deploy BACKEND
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd dev.bootcamp.tentech;
            sed -i "/BACKEND/c BACKEND_COMMIT_HASH=${{ steps.vars.outputs.sha_short }}" .env;
            docker ps -a | grep webserver;