name: Deploy to GKE

on:
  push:
    branches: ["main"]


env:
  URL: ${{ secrets.URL }}
  UPLOADS: ${{ secrets.UPLOADS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Fix
      run: |
        wget https://github.com/DawnBreather/envsubst/releases/download/v0.0.2/envsubst.linux.amd64
        mv envsubst.linux.amd64 envsubst
        chmod +x envsubst
        ./envsubst website.dockerfile
        cat website.dockerfile
        
        