name: Deploy to GKE

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Send Slack notification (start)
      uses: slackapi/slack-github-action@v1.24.0
      continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": "Начало деплоя: ${{ github.repository }} на ветке ${{ github.ref }}"
          }
          
    - name: Deploy
      run: |
        # Команда для деплоя
        echo "Deploying your application..."

    - name: Send Slack notification (end)
      if: success()
      uses: slackapi/slack-github-action@v1.24.0
      continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": "Деплой завершен: ${{ github.repository }} на ветке ${{ github.ref }}"
          }
          
    - name: Send Slack notification (failure)
      if: failure()
      uses: slackapi/slack-github-action@v1.24.0
      continue-on-error: true
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        payload: |
          {
            "text": "Ошибка деплоя: ${{ github.repository }} на ветке ${{ github.ref }}"
          }
