name: DEPRECATED Release rollout. Deployment and A-Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
        default: 'integration'
      startdeployment:
        type: boolean
        description: deploy components
        required: true
        default: false
      checkdeployment:
        type: boolean
        description: check pods before test
        required: true
        default: false
      choice:
        description: Type of Test
        type: choice
        required: true
        options:
          - REGRESSION
          - API
          - SMOKE
          - UI
          - ALL
        default: 'ALL'

permissions:
  contents: "read"
  id-token: "write"

jobs:
  rollout_release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:

      - name: "[ INFO ] Print build info"
        uses: ./.github/actions/build_info
        with:
          environment: ${{ inputs.environment }}
          choice: ${{ inputs.choice }}
          git_ref: ${{ github.ref }}
