name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

    - name: Set Trello Token for PR Author
      id: set_token
      run: |
        if [[ "${{ github.event.pull_request.user.login }}" == "aalyevn" ]]; then
          echo "TRELLO_API_KEY=${{ vars.API_KEY }}" >> $GITHUB_ENV
          echo "TRELLO_TOKEN=${{ vars.TOKEN }}" >> $GITHUB_ENV
        elif [[ "${{ github.event.pull_request.user.login }}" == "user2" ]]; then
          echo "TRELLO_API_KEY=${{ vars.TRELLO_TOKEN_USER2 }}" >> $GITHUB_ENV
          echo "TRELLO_TOKEN=${{ vars.TRELLO_TOKEN_USER1 }}" >> $GITHUB_ENV
        else
          echo "TRELLO_API_KEY=${{ vars.API_KEY_BEK }}" >> $GITHUB_ENV
          echo "TRELLO_TOKEN=${{ vars.API_KEY_EROM }}" >> $GITHUB_ENV
        fi

    - name: Echo
      run: |        
        echo ${{ env.TRELLO_API_KEY }}
        echo ${{ env.TRELLO_TOKEN }}
        echo ${{ github.event.pull_request.user.login }}
