name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    name: build
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  dev:
    name: deploy dev
    needs: [build]
    uses: ./.github/workflows/test.yml
    with:
      name: "development" 
  
  enable-dev:
    name: Enable alerts dev
    needs: [build, dev]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "disable"

  staging:
    name: deploy staging
    needs: [dev]
    uses: ./.github/workflows/test.yml
    with:
      name: "staging"

  enable-staging:
    name: Enable alerts staging
    needs: [staging]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "enable"

  training:
    name: deploy training
    needs: [staging]
    uses: ./.github/workflows/test.yml
    with:
      name: "training"
      
  enable-training:
    name: Enable alerts training
    needs: [training]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "enable"      
  