name: DEPRECATED Release rollout. Deployment and A-Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: Select the environment
        required: true
        default: 'integration'
      startdeployment:
        type: boolean
        description: deploy components
        required: true
        default: false
      checkdeployment:
        type: boolean
        description: check pods before test
        required: true
        default: false
      choice:
        description: Type of Test
        type: choice
        required: true
        options:
          - REGRESSION
          - API
          - SMOKE
          - UI
          - ALL
        default: 'ALL'

jobs:
  rollout_release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
        
      - name: "[ INFO ] Build information"
        run: |
          java -version
          mvn -version
          google-chrome --version
          helm version
          echo Deployment to ${{ inputs.environment }}
          echo Tests ${{ inputs.choice }}
          echo GitRef ${{ github.ref }}
     
      - name: Checkout code
        uses: actions/checkout@v2
