name: Deploy Nginx

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  deploy:
    name: Enable alerts
    needs: [test]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "enable" 
  
  disable:
    name: Disable
    needs: [test, deploy]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "disable"