name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    name: build
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  dev:
    name: deploy dev
    needs: [build]
    uses: ./.github/workflows/test.yml
    with:
      name: "development" 

  staging:
    name: deploy staging
    needs: [dev]
    uses: ./.github/workflows/test.yml
    with:
      name: "staging"

  staging_wait:
    name: wait staging
    needs: [staging]  # Ждем завершения staging
    uses: ./.github/workflows/test.yml
    with:
      name: "staging"
    strategy:
      matrix:
        job: [manage_alerts1]

  training:
    name: deploy training
    needs: [staging]
    uses: ./.github/workflows/test.yml
    with:
      name: "training"

  training_wait:
    name: wait training
    needs: [training]  # Ждем завершения training
    uses: ./.github/workflows/test.yml
    with:
      name: "training"
    strategy:
      matrix:
        job: [manage_alerts1]
  