name: Deploy to GKE

on:
  push:
    branches: ["main"]


env:
  URL: ${{ secrets.URL }}
  UPLOADS: ${{ secrets.UPLOADS }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Fix
      run: |
        cat website.dockerfile
        echo $URL 
        echo $UPLOADS