name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  dev:
    name: Enable alerts
    needs: [build]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "enable" 
  
  enable-dev:
    name: Disable
    needs: [build, dev]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "disable"

  staging:
    name: Test
    needs: [dev]
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  enable-staging:
    name: Test
    needs: [staging]
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"