name: Push to Gitlab
run-name: 'Push'

on:
    workflow_call:
      inputs:
        branch_name:
          required: true
          type: string
          description: "Name of the branch to delete"  

jobs:
  job:
    name: Push
    uses: aalyevn/lesson1/.github/workflows/push.yaml@main
    secrets: inherit