name: Deploy Nginx

on:
  push:
    branches:
    - 'main'

jobs:
  test:
    name: Test
    uses: ./.github/workflows/test.yml
    with:
      name: "Aalyev"

  deploy:
    name: Enable alerts
    needs: [test]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "enable" 
  
  disable:
    name: Disable
    needs: [test, deploy]
    uses: ./.github/workflows/alerts.yml
    with:
      alerts: "disable"